name: Telegram Notification

on: [push, pull_request, pull_request_review, pull_request_review_comment]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            🚀 *GitHub Notification* 🚀

            *${{ github.actor }}* triggered a *${{ github.event_name }}* event.

            Repository: *${{ github.repository }}*

            Commit by: *${{ github.actor }}*
            Commit message: *${{ github.event.head_commit.message }}*

            [See changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          format: markdown
