name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - ready_for_review
      - labeled
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set Message Content
        id: set_message
        run: |
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            echo "message=🚀 *GitHub Push Notification* 🚀%0A%0A*${{ github.actor }}* pushed to *${{ github.ref }}* branch.%0A%0ARepository: *${{ github.repository }}*%0ACommit message: *${{ github.event.head_commit.message }}*%0A%0A[See changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "message=🔃 *GitHub Pull Request Notification* 🔃%0A%0A*${{ github.actor }}* ${{ github.event.action }} pull request on *${{ github.ref }}* branch.%0A%0ARepository: *${{ github.repository }}*%0A%0A[See pull request](https://github.com/${{ github.repository }}/pull/${{ github.event.number }})" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == 'issue_comment' ]]; then
            echo "message=💬 *GitHub Pull Request Comment Notification* 💬%0A%0A*${{ github.actor }}* ${{ github.event.action }} a comment on a pull request.%0A%0ARepository: *${{ github.repository }}*%0A%0A[See comment](https://github.com/${{ github.repository }}/pull/${{ github.event.issue.number }}#issuecomment-${{ github.event.comment.id }})" >> $GITHUB_OUTPUT
          fi

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: ${{ steps.set_message.outputs.message }}
          format: markdown
          disable_web_page_preview: true
