name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - ready_for_review
      - labeled

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set Message Content
        id: set_message
        run: |
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            echo "::set-output name=message::<b>🚀 GitHub Push Notification 🚀</b><br><br><b>${{ github.actor }}</b> pushed to <b>${{ github.ref }}</b> branch.<br><br>Repository: <b>${{ github.repository }}</b><br>Event: <b>${{ github.event_name }}</b><br><br><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">See changes</a>"
          elif [[ "${{ github.event_name }}" == 'pull_request' ]]; then
            echo "::set-output name=message::<b>🔃 GitHub Pull Request Notification 🔃</b><br><br><b>${{ github.actor }}</b> ${{ github.event.action }} pull request on <b>${{ github.ref }}</b> branch.<br><br>Repository: <b>${{ github.repository }}</b><br>Event: <b>${{ github.event_name }}</b><br><br><a href=\"https://github.com/${{ github.repository }}/pull/${{ github.event.number }}\">See pull request</a>"
          fi

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: ${{ steps.set_message.outputs.message }}
          format: html
          disable_web_page_preview: true
