name: Telegram Notification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - closed
      - ready_for_review
      - labeled

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            🚀 *GitHub Notification* 🚀

            *${{ github.actor }}* triggered a *${{ github.event_name }}* event.

            Repository: *${{ github.repository }}*
            Event: *${{ github.event_name }}*

            Commit by: *${{ github.actor }}*
            Commit message: *${{ github.event.head_commit.message }}*

            [See changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          format: markdown
          disable_web_page_preview: true